imports:
    - { resource: 'parameters.yml'}
    - { resource: 'security.yml'}

sonata_media:
    contexts:
        techpromux_dynamic_query_media_image:
            providers:
                - sonata.media.provider.image

            formats:
                admin:    { width: 75, quality: 75}
                abstract: { width: 100, quality: 100}
                small:    { width: 300, quality: 100}
                large:    { width: 750, quality: 100}
                wide:     { width: 820, quality: 100}   

sonata_admin:
    dashboard:
        blocks:
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [techpromux_dynamic_queries_admin] } }

        groups:
            techpromux_dynamic_queries_admin:
                label: Dynamic Queries
                label_catalogue: TechPromuxDynamicQueryBundle
                icon: '<i class="glyphicon glyphicon-cog"></i>'
                items:
                    - techpromux_dynamic_query.admin.datasource
                    - techpromux_dynamic_query.admin.metadata
                    - techpromux_dynamic_query.admin.datamodel

