services:

    # Admin services

    techpromux_dynamic_query.admin.datasource:
        class:  TechPromux\DynamicQueryBundle\Admin\DataSourceAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\DataSource, TechPromuxDynamicQueryBundle:DataSourceAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_datasource_list }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.datasource']]

    techpromux_dynamic_query.admin.metadata:
        class:  TechPromux\DynamicQueryBundle\Admin\MetadataAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\Metadata, TechPromuxDynamicQueryBundle:MetadataAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_metadata_list }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.metadata']]

    techpromux_dynamic_query.admin.metadata_table:
        class:  TechPromux\DynamicQueryBundle\Admin\MetadataTableAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\MetadataTable, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_metadata_table_list, show_in_dashboard: false }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.metadata_table']]

    techpromux_dynamic_query.admin.metadata_field:
        class:  TechPromux\DynamicQueryBundle\Admin\MetadataFieldAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\MetadataField, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_metadata_field_list, show_in_dashboard: false }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.metadata_field']]

    techpromux_dynamic_query.admin.metadata_relation:
        class:  TechPromux\DynamicQueryBundle\Admin\MetadataRelationAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\MetadataRelation, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_metadata_relation_list, show_in_dashboard: false }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.metadata_relation']]

    techpromux_dynamic_query.admin.datamodel:
        class:  TechPromux\DynamicQueryBundle\Admin\DataModelAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\DataModel, TechPromuxDynamicQueryBundle:DataModelAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_datamodel_list }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.datamodel']]

    techpromux_dynamic_query.admin.datamodel_detail:
        class:  TechPromux\DynamicQueryBundle\Admin\DataModelDetailAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\DataModelDetail, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_datamodel_detail_list, show_in_dashboard: false }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.datamodel_detail']]

    techpromux_dynamic_query.admin.datamodel_group:
        class:  TechPromux\DynamicQueryBundle\Admin\DataModelGroupAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\DataModelGroup, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_datamodel_group_list, show_in_dashboard: false }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.datamodel_group']]

    techpromux_dynamic_query.admin.datamodel_condition:
        class:  TechPromux\DynamicQueryBundle\Admin\DataModelConditionAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\DataModelCondition, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_datamodel_condition_list, show_in_dashboard: false }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.datamodel_condition']]

    techpromux_dynamic_query.admin.datamodel_order:
        class:  TechPromux\DynamicQueryBundle\Admin\DataModelOrderAdmin
        arguments: [~,  TechPromux\DynamicQueryBundle\Entity\DataModelOrder, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_queries_admin, label: sidebar.link_datamodel_list, show_in_dashboard: false }
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicQueryBundle']]
            - [ setResourceManager,['@techpromux_dynamic_query.manager.datamodel_order']]

