services:
    # Conditional Operator Types Services

    techpromux_dynamic_query.type.conditional_operator.unary.IsTrue:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Unary\IsTrueConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.unary.IsNotTrue:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Unary\IsNotTrueConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.unary.IsFalse:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Unary\IsFalseConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.unary.IsNotFalse:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Unary\IsNotFalseConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.unary.IsNull:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Unary\IsNullConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.unary.IsNotNull:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Unary\IsNotNullConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.unary.IsEmpty:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Unary\IsEmptyConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.unary.IsNotEmpty:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Unary\IsNotEmptyConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.Equal:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\EqualConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.NotEqual:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\NotEqualConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.LessThan:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\LessThanConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.LessOrEqual:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\LessOrEqualConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.GreaterThan:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\GreaterThanConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.GreaterOrEqual:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\GreaterOrEqualConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.Between:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\BetweenConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.NotBetween:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\NotBetweenConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.In:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\InConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.NotIn:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\NotInConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.Contains:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\ContainsConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.NotContains:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\NotContainsConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.NotStartsWith:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\NotStartsWithConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.StartsWith:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\StartsWithConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.EndsWith:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\EndsWithConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.NotEndsWith:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\NotEndsWithConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.Like:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\LikeConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

    techpromux_dynamic_query.type.conditional_operator.binary.NotLike:
        class:  TechPromux\DynamicQueryBundle\Type\ConditionalOperator\Binary\NotLikeConditionalOperatorType
        tags:
            - { name: techpromux_dynamic_query.type.conditional_operator}

