services:
    # Manager Services

    techpromux_dynamic_query.manager.util_dynamic_query:
        class:  TechPromux\DynamicQueryBundle\Manager\UtilDynamicQueryManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setSecurityManager,['@techpromux.manager.default_security']]

    techpromux_dynamic_query.manager.datasource:
        class:  TechPromux\DynamicQueryBundle\Manager\DataSourceManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setResourceContextManager,['@techpromux.manager.default_resource_context']]
            - [ setUtilDynamicQueryManager,['@techpromux_dynamic_query.manager.util_dynamic_query']]
            - [ setConnectionFactory,['@doctrine.dbal.connection_factory']]

    techpromux_dynamic_query.manager.metadata:
        class:  TechPromux\DynamicQueryBundle\Manager\MetadataManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setResourceContextManager,['@techpromux.manager.default_resource_context']]
            - [ setUtilDynamicQueryManager,['@techpromux_dynamic_query.manager.util_dynamic_query']]
            - [ setDataSourceManager,['@techpromux_dynamic_query.manager.datasource']]
            - [ setMetadataTableManager,['@techpromux_dynamic_query.manager.metadata_table']]
            - [ setMetadataFieldManager,['@techpromux_dynamic_query.manager.metadata_field']]
            - [ setMetadataRelationManager,['@techpromux_dynamic_query.manager.metadata_relation']]

    techpromux_dynamic_query.manager.metadata_table:
        class:  TechPromux\DynamicQueryBundle\Manager\MetadataTableManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setMetadataManager,['@techpromux_dynamic_query.manager.metadata']]

    techpromux_dynamic_query.manager.metadata_relation:
        class:  TechPromux\DynamicQueryBundle\Manager\MetadataRelationManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setMetadataManager,['@techpromux_dynamic_query.manager.metadata']]

    techpromux_dynamic_query.manager.metadata_field:
        class:  TechPromux\DynamicQueryBundle\Manager\MetadataFieldManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setMetadataManager,['@techpromux_dynamic_query.manager.metadata']]

    techpromux_dynamic_query.manager.datamodel:
        class:  TechPromux\DynamicQueryBundle\Manager\DataModelManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setResourceContextManager,['@techpromux.manager.default_resource_context']]
            - [ setMetadataManager,['@techpromux_dynamic_query.manager.metadata']]
            - [ setDatamodelDetailManager,['@techpromux_dynamic_query.manager.datamodel_detail']]
            - [ setDatamodelGroupManager,['@techpromux_dynamic_query.manager.datamodel_group']]
            - [ setDatamodelConditionManager,['@techpromux_dynamic_query.manager.datamodel_condition']]
            - [ setDatamodelOrderManager,['@techpromux_dynamic_query.manager.datamodel_order']]
            - [ setUtilDynamicQueryManager,['@techpromux_dynamic_query.manager.util_dynamic_query']]

    techpromux_dynamic_query.manager.datamodel_detail:
        class:  TechPromux\DynamicQueryBundle\Manager\DataModelDetailManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setDataModelManager,['@techpromux_dynamic_query.manager.datamodel']]

    techpromux_dynamic_query.manager.datamodel_group:
        class:  TechPromux\DynamicQueryBundle\Manager\DataModelGroupManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setDataModelManager,['@techpromux_dynamic_query.manager.datamodel']]

    techpromux_dynamic_query.manager.datamodel_condition:
        class:  TechPromux\DynamicQueryBundle\Manager\DataModelConditionManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setDataModelManager,['@techpromux_dynamic_query.manager.datamodel']]

    techpromux_dynamic_query.manager.datamodel_order:
        class:  TechPromux\DynamicQueryBundle\Manager\DataModelOrderManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setDataModelManager,['@techpromux_dynamic_query.manager.datamodel']]

