services:
#    tech_promux_dynamic_query.example:
#        class: TechPromux\Bundle\DynamicQueryBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    # Types JOIN Services

    techpromux_dynamic_query.type.join.inner:
        class: TechPromux\Bundle\DynamicQueryBundle\Type\Relation\InnerJoinType
        tags:
            - { name: techpromux_dynamic_query.type.join}

    techpromux_dynamic_query.type.join.left:
        class: TechPromux\Bundle\DynamicQueryBundle\Type\Relation\LeftJoinType
        tags:
            - { name: techpromux_dynamic_query.type.join}

