imports:
    - { resource: 'services_types_table_relation.yml'}
    - { resource: 'services_managers.yml'}
    - { resource: 'services_admins.yml'}

services:
#    tech_promux_dynamic_query.example:
#        class: TechPromux\Bundle\DynamicQueryBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

