imports:
    - { resource: 'types.yml'}
    - { resource: 'managers.yml'}
    - { resource: 'admins.yml'}

services:
#    tech_promux_dynamic_query.example:
#        class: TechPromux\Bundle\DynamicQueryBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

