services:
#    tech_promux_dynamic_query.example:
#        class: TechPromux\Bundle\DynamicQueryBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    # Types JOIN Services

    techpromux_dynamic_query.type.table_relation.inner:
        class: TechPromux\Bundle\DynamicQueryBundle\Type\TableRelation\InnerJoinTableRelationType
        tags:
            - { name: techpromux_dynamic_query.type.table_relation}

    techpromux_dynamic_query.type.table_relation.left:
        class: TechPromux\Bundle\DynamicQueryBundle\Type\TableRelation\LeftJoinTableRelationType
        tags:
            - { name: techpromux_dynamic_query.type.table_relation}

